---
# handlers file for slacko_role

- name: "started slacko-api.service" 
  ansible.builtin.systemd:
    name: slacko-api.service
    state: started
    enable: yes 
    
- name: "enable mongodb"
  ansible.builtin.systemd:
    name: mongodb
    state: started
    enable: yes
